###############################################################################
# DEB post install script. Generated by AppForge (https://theappforge.io)
################################################################################

#! /bin/bash

echo "Running post installation script"
chmod 777 /opt/${appSafeName}
ln -s /opt/${appSafeName}/${appSafeName}.desktop /usr/share/applications/${appSafeName}.desktop
