###############################################################################
# DEB post un-install script. Generated by AppForge (https://theappforge.io)
################################################################################

#! /bin/bash

echo "Running post uninstall script"
rm /usr/share/applications/${appSafeName}.desktop
