###############################################################################
# RPM build spec file generated by AppForge (https://theappforge.io)
################################################################################

Name: ${appSafeName}
Version: ${rpmVersion}
Summary: ${comment}
Buildarch: ${cpuArch}
<#if appUrl?has_content>
URL: ${appUrl}
</#if>
Group: Development
Release: ${rpmRelease}
License: Proprietary

%description
${description}

%files
/opt/${appSafeName}/

%post
APPFORGE_GROUP_NAME="appforge"
echo "Running post installation script"
groupadd -f $APPFORGE_GROUP_NAME
chgrp -Rv $APPFORGE_GROUP_NAME /opt/${appSafeName}
find /opt/${appSafeName} -type d -exec chmod g+s {} \;
ln -s /opt/${appSafeName}/${appSafeName}.desktop /usr/share/applications/${appSafeName}.desktop

%postun
rm /usr/share/applications/${appSafeName}.desktop
