###############################################################################
# RPM build spec file generated by AppForge (https://theappforge.io)
################################################################################

Name: ${appSafeName}
Version: ${rpmVersion}
Summary: ${comment}
Buildarch: ${cpuArch}
<#if appUrl?has_content>
URL: ${appUrl}
</#if>
Group: Development
Release: ${rpmRelease}
License: Proprietary

%description
${description}

%files
/opt/${appSafeName}/

%post
echo "Running post install script"
chmod 777 /opt/${appSafeName}
ln -s /opt/${appSafeName}/${appSafeName}.desktop /usr/share/applications/${appSafeName}.desktop

%postun
rm /usr/share/applications/${appSafeName}.desktop
