name: Perform code verification
on:
  pull_request:
    branches: [ master ]
jobs:
  build-and-test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and test
        run: |
          mvn -Dgpg.skip clean verify
